### ISSUE TITLE
0.7.0 crashes when added with certain mods (from comments)

### ISSUE THREAD

**Issue by SaishoVibes** [SaishoVibes/Back-in-Classic#19]
[15:42:56] [pool-3-thread-1/ERROR] [or.jm.mc.mo.FastUtilTransformerService/JMTSUPERTRANS]: Inner class faliure; parent not found

[15:42:56] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:

[15:42:56] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: java.lang.reflect.InvocationTargetException

[15:42:56] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[15:42:56] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[15:42:56] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[15:42:56] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: at java.lang.reflect.Method.invoke(Method.java:498)

[15:42:56] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)

[15:42:56] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)

[15:42:56] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: at org.multimc.EntryPoint.listen(EntryPoint.java:143)

[15:42:56] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: at org.multimc.EntryPoint.main(EntryPoint.java:34)

[15:42:56] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: Caused by: java.lang.reflect.InvocationTargetException

[15:42:56] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[15:42:56] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[15:42:56] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[15:42:56] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: at java.lang.reflect.Method.invoke(Method.java:498)

[15:42:56] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)

[15:42:56] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: ... 8 more

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: ... 13 more

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: Caused by: java.lang.reflect.InvocationTargetException

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: at java.lang.reflect.Method.invoke(Method.java:498)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: ... 17 more

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: net/minecraftforge/common/ForgeHooks

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:43)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at net.minecraft.client.main.Main.main(Main.java:123)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: ... 23 more

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/common/ForgeHooks

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at net.minecraft.block.Block.<clinit>(Block.java:485)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at net.minecraft.block.Blocks.<clinit>(Blocks.java:30)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:33)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at net.minecraft.client.main.Main.lambda$main$0(Main.java:123)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at java.lang.Thread.run(Thread.java:750)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: Caused by: java.lang.ClassNotFoundException: net.minecraftforge.common.ForgeHooks

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at java.lang.ClassLoader.findClass(ClassLoader.java:523)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at java.lang.ClassLoader.loadClass(ClassLoader.java:418)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: ... 16 more

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: Suppressed: java.lang.SecurityException: class "net.minecraftforge.common.ForgeHooks"'s signer information does not match signer information of other classes in the same package

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at java.lang.ClassLoader.checkCerts(ClassLoader.java:891)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at java.lang.ClassLoader.preDefineClass(ClassLoader.java:661)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at java.lang.ClassLoader.defineClass(ClassLoader.java:754)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)

[15:42:56] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: ... 17 more

[15:42:56] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1

**Comment by Asbestosstar** [comment]
Hi, i tried 0.8 Release, same issue

**Comment by SaishoVibes** [comment]
> 

Could I have the mod list? I want to do testing on my own end so I can get my full console.

**Comment by SaishoVibes** [comment]
if it is easier, dm me on discord (Saisho サイショ#0521) so we can talk easier?

**Comment by SaishoVibes** [comment]
Due to lack of info I am closing this for now since I am 2 versions ahead now.
